### ISSUE TITLE
Could you tell me how to accumulate lidar data?

### ISSUE THREAD

**Issue by Fred159** [inkyusa/cartographer_kitti_config#2]
I played your demo and run mine. However, I don't know how to accumulate point data in rviz just like your https://www.youtube.com/watch?v=29Knm-phAyI&feature=youtu.be . 
The point cloud shown just for moment and disappear when new point cloud comes in.

**Comment by inkyusa** [comment]
Hello,
Thanks for your interests. Looking at RVIZ scan topic (on the left side of the window), there is "Delay Time" and increasing this will accumulate 'drifting' scans.
http://wiki.ros.org/rviz/DisplayTypes/LaserScan
Hope this help.
Best,

**Comment by Fred159** [comment]
> Hello,
> Thanks for your interests. Looking at RVIZ scan topic (on the left side of the window), there is "Delay Time" and increasing this will accumulate 'drifting' scans.
> http://wiki.ros.org/rviz/DisplayTypes/LaserScan
> Hope this help.
> Best,

Thank you so much.!!!
